### ISSUE TITLE
Is the original XCoffee source code available?

### ISSUE THREAD

**Issue by BRGustavoRibeiro** [ijl20/cambridge_coffee_pot#1]
Yeah, the really old one.
I don't know why but I would love to take a look at it.

**Comment by ijl20** [comment]
Nope - I checked with Quentin Stafford-Fraser who worked on the original XCoffee code back in the day, and that code has evaporated with Quentin commenting "it was so dependent on our own libraries, ATM network stack and RPC mechanisms that I can't imagine it would be of much use to anyone! And the server side ran on our ATMOS operating system..."

**Comment by BRGustavoRibeiro** [comment]
That's sad :cry: 

Even by the heavy usage of internal libraries, I feel that this is a part of computer history that is relevant enough to be archived. Thanks for the answer, though! :+1:
